### ISSUE TITLE
[Feature Request] improve cli client with same options as web interface.

### ISSUE THREAD

**Issue by srgvg** [Cesura/pastey#9]
I would like to improve the client cli application, to be able to (optionally) also choose ecnryption, single use, and set a title, the expiry. I had a look at the curl command, and compared it with the curl command I get from copying it from the web made request via browser devtools, but I'm not sure how to go forth from there, and how `/raw` and `/paste` endpoints exactly behave differently.

Given some pointers or info, I'm willing to work on that.

**Comment by Cesura** [comment]
Yeah it would be great if you improved the script. It's something I've been meaning to do but haven't gotten around to yet.

The primary difference between /raw and /paste is that /raw accepts the plain body from the HTTP request, and /paste takes form elements. So, it seems to me that these could maybe be passed via curl with the -F flag:
`curl -X POST -F 'title=Post title' -F 'encrypt=' http://pastey-url.com/paste`

The form elements currently are:
* title
* content
* encrypt
* single
* expiration

**encrypt** and **single** only need to be present if they're enabled, without any values. **expiration** should be the expiration time in hours. If the **title** is empty, the /paste endpoint will default to "Untitled", like it does now; it still needs to be present though.

Hopefully this helps a bit? :)

**Comment by srgvg** [comment]
Yeah, I somehow suspected this difference. Looking at the curlized command from devtools, it translated the content into urlized content. Would that be needed too, or can I  do `-f 'content=${CONTENT}` as in your script?

**Comment by Cesura** [comment]
I just tested it and I was able to get it to work with:
`curl -X POST -F 'content=test' -F 'title=' -F 'expiration=-1' http://localhost:5000/paste`

However, right now /paste returns an HTTP redirect, rather than the link like /raw does. So, I think I need to change /paste to accept a form element named "raw" or something, which will return the link rather than the redirect if it is present, or modify the existing /raw endpoint to accept either json or form elements, and update the script to reflect that. I guess option 1 is more reasonable, as it would remove the need for separate endpoints?

EDIT: To your question, I think passing it as you wrote should work.

**Comment by srgvg** [comment]
OK, I'll see in the coming days when I find some time to tinker with that. Do you have any preferences about the format? By that I mean, how to define options etc.?

**Comment by Cesura** [comment]
I just fixed some things in 0.4.1, hopefully this will help:
* /paste now returns a link instead of a redirect if the form option 'cli' is included
* New endpoint /json accepts json-formatted bodies (see the bottom of the /config page for a few more details)

As for which of those endpoints you'd like to use in the script, that's completely up to you. In my mind it would function like this:
`$ cat /var/log/nginx.log | pastey --title "Nginx log" --encrypted`
and
`$ pastey /var/log/nginx.log --title "Nginx log" --encrypted`
and
`$ pastey /var/log/nginx.log`
which would set the title to "/var/log/nginx.log"

In reality though you can feel free to implement it however you see fit. I would just prefer to not lose the ability to pipe from stdin.
